# autogenerated by txs
\absleftindent
\absnamepos#S
\absparindent
\absparsep
\absrightindent
\abstitleskip
\abstitlestyle{arg1}#S
\abstractnamefont#S
\abstracttextfont#S
\appendiargdef{arg1}{arg2}#S
\begin{onecolabstract}#S
\end{onecolabstract}#S
\saythanks#S
\abslabeldelim#S
