# autogenerated by txs
#include:fontaxes
#include:fontenc
#include:fontspec
#include:ifluatex
#include:ifxetex
#include:mweights
#include:textcomp
#include:xkeyval
\cormorantgaramond#S
\infigures#S
\seriesdefault#S
\sufigures#S
\liningnums #S
\liningnums#S
\proportionalnums #S
\proportionalnums#S
\tabularnums #S
\tabularnums#S
\textinf #S
\textinf#S
\textsu #S
\textsu#S
fontaxes.sty#S
fontenc.sty#S
ifluatex.sty#S
ifxetex.sty#S
textcomp.sty#S
xkeyval.sty#S
