# autogenerated by txs
#include:infwarerr
\HyphSubstIfExists{arg1}#S
\HyphSubstLet{arg1}{arg2}#S
\MessageBreak#S
\check{arg1}#S
\csname#S
\empty#S
\expandafter#S
\lmsg#S
\msg#S
\space#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
infwarerr.sty#S
