# autogenerated by txs
#include:etoolbox
\LR#S
\LRE#S
\LTR#S
\RL#S
\RLE#S
\RTL#S
\bracetext#S
\endLTR#S
\endRTL#S
\hboxR{arg1}#S
\moreLRE#S
\moreRLE#S
\pLRE#S
\pRLE#S
\setLR#S
\setLTR#S
\setRL#S
\setRTL#S
\setRTLmain#S
\unsetLTR#S
\unsetRTL#S
\LRE #S
\RLE #S
\begin{LTR}
\begin{RTL}
\end{LTR}
\end{RTL}
etoolbox.sty#S
