# autogenerated by txs
#include:ifthen
#include:multicol
\immediateaddtocontents{arg1}{arg2}#S
\label#S
\multicolumnlof#S
\multicolumnlot#S
\multicolumntoc#S
\protect#S
\thepage#S
ifthen.sty#S
multicol.sty#S
