# autogenerated by txs
#include:fontspec
\fakesubscript{arg1}#S
\fakesuperscript{arg1}#S
\realsubscript{arg1}#S
\realsuperscript{arg1}#S
\textsubsuperscript*[optarg2]{arg3}#S
\textsubsuperscript*{arg2}#S
\textsubsuperscript[optarg1]{arg2}#S
\textsubsuperscript{arg1}#S
\textsupersubscript*[optarg2]{arg3}#S
\textsupersubscript*{arg2}#S
\textsupersubscript[optarg1]{arg2}#S
\textsupersubscript{arg1}#S
